        --Item ID Definitions-- 

--Usage:    local ids = require("ids")
--          print(ids.cobblestone)

--Output    minecraft:cobblestone


 local item_ids = {
--Cobble Farm
 andesite = "minecraft:andesite",
 andesitealloy = "create:andesite_alloy",
 blackstone = "minecraft:blackstone",
 brick = "minecraft:brick",
 bricks = "minecraft:bricks",
 clay = "minecraft:clay",
 clayball = "minecraft:clay_ball",
 cobblestone = "minecraft:cobblestone",
 deadbush = "minecraft:dead_bush",
 diorite = "minecraft:diorite",
 dirt = "minecraft:dirt",
 flint = "minecraft:flint",
 glass = "minecraft:glass",
 goldnugget = "minecraft:gold_nugget",
 goldingot = "minecraft:gold_ingot",
 goldblock = "minecraft:gold_block",
 goldsheet = "create:golden_sheet",
 granite = "minecraft:granite",
 gravel = "minecraft:gravel",
 ironnugget = "minecraft:iron_nugget",
 ironingot = "minecraft:iron_ingot",
 ironblock = "minecraft:iron_block",
 ironsheet = "create:iron_sheet",
 netherbrick = "minecraft:nether_brick",
 netherbricks = "minecraft:nether_bricks",
 quartz = "minecraft:quartz",
 quartzblock = "minecraft:quartz_block",
 redsand = "minecraft:red_sand",
 sand = "minecraft:sand",
 smoothstone = "minecraft:smooth_stone",
 smoothquartzblock = "minecraft:smooth_quartz",
 soulsand = "minecraft:soul_sand",
 soulsoil = "minecraft:soul_soil",
 stone = "minecraft:stone",
 terracotta = "minecraft:terracotta",

            --Plant Farms--

--Wood
 oaksapling = "minecraft:oak_sapling",
 birchsapling = "minecraft:birch_sapling",
 sprucesapling = "minecraft:spruce_sapling" ,
 darkoaksapling = "minecraft:dark_oak_sapling",
 junglesapling = "minecraft:jungle_sapling",
 acaciasapling = "minecraft:acacia_sapling",
 cherrysapling = "minecraft:cherry_sapling",
 propagule = "minecraft:mangrove_propagule",
 oaklog = "minecraft:oak_log",
 birchlog = "minecraft:birch_log",
 sprucelog = "minecraft:spruce_log",
 junglelog = "minecraft:jungle_log",
 acacialog = "minecraft:acacia_log",
 darkoaklog = "minecraft:dark_oak_log",
 cherrylog = "minecraft:cherry_log",
 mangrovelog = "minecraft:mangrove_log",
 mangroveroots = "minecraft:mangrove_roots",
 bamboo = "minecraft:bamboo",
 stick = "minecraft:stick",
 crimsonstem = "minecraft:crimson_stem",
 warpedstem = "minecraft:warped_stem",

--Moss Farm
 mosscarpet = "minecraft:moss_carpet",
 moss = "minecraft:moss_block",
 azalea = "minecraft:azalea",
 floweringazalea = "minecraft:flowering_azalea",
 wheatseeds = "minecraft:wheat_seeds",
 bonemeal = "minecraft:bone_meal",
 boneblock = "minecraft:bone_block",


--Crops
 wheat = "minecraft:wheat",
 haybale = "minecraft:hay_block",
 potato = "minecraft:potato",
 poisonouspotato = "minecraft:poisonous_potato",
 potatocrate = "farmersdelight:potato_crate",
 carrot = "minecraft:carrot",
 carrotcrate = "farmersdelight:carrot_crate",
 beetroot = "minecraft:beetroot",
 beetrootcrate = "farmersdelight:beetroot_crate",
 beetrootseeds = "minecraft:beetroot_seeds",
 onion = "farmersdelight:onion",
 onioncrate = "farmersdelight:onion_crate",
 tomato = "farmersdelight:tomato",
 rottentomato = "farmersdelight:rotten_tomato",
 tomatocrate = "farmersdelight:tomato_crate",
 tomatoseeds = "farmersdelight:tomato_seeds",
 cabbage = "farmersdelight:cabbage",
 cabbagecrate = "farmersdelight:cabbage_crate",
 cabbageseeds = "farmersdelight:cabbage_seeds",
 ricepanicle = "farmersdelight:rice_panicle",
 ricebale = "farmersdelight:rice_bale",
 flax = "supplementaries:flax",
 flaxbale = "supplementaries:flax_block",
 flaxseeds = "supplementaries:flax_seeds",
 melon = "minecraft:melon",
 melonslice = "minecraft:melon_slice",
 melonseeds = "minecraft:melon_seeds",
 pumpkin = "minecraft:pumpkin",
 pumpkinseeds = "minecraft:pumpkin_seeds",
 kelp = "minecraft:kelp",
 driedkelp = "minecraft:dried_kelp",
 driedkelpblock = "minecraft:dried_kelp_block",
 cactus = "minecraft:cactus",
 sugarcane = "minecraft:sugar_cane",
 apple = "minecraft:apple",
 sweetberries = "minecraft:sweet_berries",
 glowberries = "minecraft:glow_berries",
 cocoabeans = "minecraft:cocoa_beans",

--Mushrooms
 brownmushroom = "minecraft:brown_mushroom",
 redmushroom = "minecraft:red_mushroom",
 crimsonfungus = "minecraft:crimson_fungus",
 warpedfungus = "minecraft:warped_fungus",

 charcoal = "minecraft:charcoal",
 charcoalblock = "sbmcharcoalblock:charcoal_block",
}
return item_ids